### ISSUE TITLE
Integrating with vpm

### ISSUE THREAD

**Issue by hovsater** [tomtom/enabler_vim#1]
I'm currently working on a standalone plugin manager for Vim. See http://kevinsjoberg.com/vim-plugin-manager-vpm for more information.

[vpm](https://github.com/KevinSjoberg/vpm/tree/vpm-go) handles inserting, updating and removing plugins, leaving plugin bootstrapping to a Vim plugin. Currently it relies on [pathogen](https://github.com/tpope/vim-pathogen) for doing this.

I'm exploring other alternatives. Leaving the choice of what plugin to use for bootstrapping to the user. What would be required of vpm in order to be compatible with enabler_vim? Currently vpm works by inserting plugins into the `~/.vim/bundle` directory.

**Comment by tomtom** [comment]
> I'm exploring other alternatives. Leaving the choice of what plugin to 
> use for bootstrapping to the user. What would be required of vpm in 
> order to be compatible with enabler_vim? Currently vpm works by 
> inserting plugins into the |~/.vim/bundle| directory. 

Sounds like a perfect match for enabler_vim. Enabler should work out of 
the box since it also uses the bundle subdir. If you want to use 
enabler's :Autoenabler command, you have to run :Enablergenerate after 
updating your plugins.

Regards,
Tom
